receivers:
  prometheus:
    config:
      global:
        scrape_interval: 30s
        scrape_timeout: 10s
      scrape_configs:
      - job_name: "adot-sidecar-scrape-application"
        static_configs:
        - targets: [ "127.0.0.1:$APPLICATION_PORT" ]
        honor_labels: true
        honor_timestamps: true

processors:

exporters:
  prometheusremotewrite:
    endpoint: $PROMETHEUS_ENDPOINT_URL
    resource_to_telemetry_conversion:
        enabled: false
    auth:
      authenticator: sigv4auth
  logging:
    loglevel: info

extensions:
  sigv4auth:
    region: $AWS_REGION
    service: aps
    assume_role:
      arn: $PROMETHEUS_WRITE_ASSUME_ROLE_ARN

service:
  telemetry:
    logs:
      level: $OTEL_LOG_LEVEL
    metrics:
      level: none
  extensions: [sigv4auth]
  pipelines:
    metrics/application:
      receivers: [prometheus]
      exporters: [logging, prometheusremotewrite]
