name: Build and test

on:
  workflow_call:
  pull_request:

permissions:
  contents: read

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
      - name: Detect secrets
        uses: alphagov/pay-ci/actions/detect-secrets@master

  build-and-test:
    name: Container Build Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
      - name: Docker build
        run: |
          docker build -t pay-adot:github-tests .
      - name: Run tests
        working-directory: tests/
        run: ./test.sh

  check-docker-base-images-are-manifests:
    uses: alphagov/pay-ci/.github/workflows/_validate_docker_image_is_manifest.yml@master
